### ISSUE TITLE
Feature request - Reviewer profile picture

### ISSUE THREAD

**Issue by cristeacosmin** [apify-projects/store-crawler-google-places#100]
In the div: .section-review-content you can find an image of the reviewer ( cropped ) having this class: .section-review-reviewer-image

Although the image is at 36px width and height, you can request for a bigger image by changing the following params: w36-h36

**Comment by metalwarrior665** [comment]
I will add it to the code but not to the default output as we will remove few other fields to make to better with GDPR.

**Comment by metalwarrior665** [comment]
Done
