### ISSUE TITLE
Add option to allow duplicates cross 'start urls'

### ISSUE THREAD

**Issue by pocesar** [apify-projects/store-crawler-google-places#173]
Would be a new input schema option that allows duplicates to appear in different start URLs, that each contain a separate term, but can have the same places in other URLs. the important part is to be able to get the search term tied to the listing, even if it's a duplicate. 

for example, beer, pub, liquor, all have something in common, in the same area, might yield the same listings. would be desirable to have them duplicated for each term

**Comment by metalwarrior665** [comment]
I would say this is super niche and would suggest separate runs for each query in that case
