### ISSUE TITLE
Keep printing WARN  [SEARCH]: Cannot find place data in search. for the same URL

### ISSUE THREAD

**Issue by sergemarkin** [apify-projects/store-crawler-google-places#202]
Got into infinite loop. Crawler keeps printing `WARN  [SEARCH]: Cannot find place data in search. for the same URL`.
Because of that, actor hangs and can not complete. It spends my paid resources and make it impossible to finish the scan.

There was opened issue #132 but it was closed without resolution.

**Comment by metalwarrior665** [comment]
This was the original fix I think - https://github.com/drobnikj/crawler-google-places/commit/f44151c070537dd11cec67f9c607573af94f1372

Will explore the root cause also so we can finally get rid of this
