### ISSUE TITLE
Google place description field missing

### ISSUE THREAD

**Issue by alexpluto** [apify-projects/store-crawler-google-places#218]
Hi there,

I was wondering if there was a reason the description field wasn't returned by this service?

e.g. 
<img width="950" alt="Screenshot 2021-11-28 at 15 09 01" src="https://user-images.githubusercontent.com/42174498/143773770-858a87f6-1c55-4e09-82a0-9f8287a79236.png">

With other similar services this is returned, so I was just interested.

Apart from that field, this is a great service!

**Comment by HamzaAlwan** [comment]
Here is the [pull request](https://github.com/apify-projects/store-crawler-google-places/pull/329)

**Comment by metalwarrior665** [comment]
done
