### ISSUE TITLE
Extract booking options for accomodations

### ISSUE THREAD

**Issue by hectorgm** [apify-projects/store-crawler-google-places#233]
Hi,

In the same way there is the OrderBy column, would it be possible to extract the booking options for accomodations?

Regards,

Hector

![image](https://user-images.githubusercontent.com/12633036/150747117-12f2787b-9fc3-4a62-b27d-becb78de7638.png)

**Comment by metalwarrior665** [comment]
Good idea!

**Comment by HamzaAlwan** [comment]
Here is the [pull request](https://github.com/apify-projects/store-crawler-google-places/pull/329)

**Comment by metalwarrior665** [comment]
This was just added
