### ISSUE TITLE
`maxOpenPagesPerBrowser` ignored in certain cases

### ISSUE THREAD

**Issue by hectorgm** [apify-projects/store-crawler-google-places#236]
**Describe the bug**
When running a large extraction on a medium size server (16 cores, 128GB RAM) without limiting the maximum concurrency, the scraper starts to open several tabs at the same time on the same browser, although the `maxOpenPagesPerBrowser` is set to `1`. This leads to timeout and session closed errors.

![image](https://user-images.githubusercontent.com/12633036/151755656-19d23d22-1ed1-4470-ad02-b28970d8ad63.png)

It might be related to this issue [Some browserPoolOptions in puppeteerCrawler are ignored in certain cases](https://github.com/apify/apify-js/issues/1126) that came from the `browser-pool` library, and that was fixed in this pull request [fix: race condition on `newPage`](https://github.com/apify/browser-pool/pull/44).

**To Reproduce**
Run a large extraction without limiting the maximum concurrency and setting the `maxOpenPagesPerBrowser` to `1`.

**Expected behavior**
The scraper makes the extraction without any issues, opening only one page per browser

**Comment by metalwarrior665** [comment]
We updated the SDK version and it seems to be working correctly now
