### ISSUE TITLE
reviews sort by ranking broken

### ISSUE THREAD

**Issue by zpelechova** [apify-projects/store-crawler-google-places#265]
The actor doesnt return any reviews when sorted by lowest ranking. https://console.apify.com/view/runs/zostGe3KAAGzP1ckw

**Comment by HamzaAlwan** [comment]
@zpelechova I ran the actor with your input multiple times, and for each one, I got 10 reviews (as set in the input), so it seems its working fine.

Here is one of the [runs](https://console.apify.com/actors/EsSrXcZXUgAlv3HEB/runs/wrsbJti7ADmEUCmHl#output)

**Comment by metalwarrior665** [comment]
@HamzaAlwan Can you test with more reviews and check if it matches the order and count? This used to break at one point but maybe it was just bugged on Google Maps themselves.

**Comment by HamzaAlwan** [comment]
@metalwarrior665  I have tested this multiple times and it's working fine, and the reviews are sorted correctly.

**Comment by metalwarrior665** [comment]
Great, thanks, closing this
