### ISSUE TITLE
Not all images getting captured

### ISSUE THREAD

**Issue by akshit-scapia** [apify-projects/store-crawler-google-places#273]
Hi are you sure that all images are being scraped, I ran on apify platform and only max 4 images were getting crawled for any place irrespective of `maxImages` input. I changed the line: https://github.com/drobnikj/crawler-google-places/blob/master/src/extractors/images.js#L72 
to: `scrollTo(page, '.dS8AEf', pageBottom),`
and now all images were getting scraped. I don't know if `section-scrollbox` class exists anymore as I couldn't find it on inspect element.

**Comment by metalwarrior665** [comment]
Forgot to close, this was fixed while ago.
