### ISSUE TITLE
Extracting most places' ids from a certain city/country

### ISSUE THREAD

**Issue by tcaram** [apify-projects/store-crawler-google-places#303]
Hi there.

I've been trying this crawler for a few days but I can't yet find the proper inputs to maxify the amount of results. I've tried both search terms, moving mouse and OCR. So far OCR has been the most efficient approach, with 12k results in a 1M population city using zoom=18.. though it's still very far from what I'm looking for.

What settings would you recommend if I'm just looking to extract places' ids?

**Comment by metalwarrior665** [comment]
So you are looking to extract maximum number of any type of places from a city? I You can increase the zoom even further, some places are only displayed with zoom 20 or 21. Another option is to use a list of keywords with lower zoom

**Comment by metalwarrior665** [comment]
I will close this for now but feel free to ask further
