### ISSUE TITLE
Filtering reviews by a keyword

### ISSUE THREAD

**Issue by mkmenta** [apify-projects/store-crawler-google-places#304]
Feature request: Would it be possible to add the option of just scraping the reviews that contain a keyword? Like this:
<img width="385" alt="screenshot" src="https://user-images.githubusercontent.com/18461246/191178614-92011967-b550-446a-b6c1-93690af3c2fb.png">

Thank you so much!

**Comment by metalwarrior665** [comment]
Hello, this should be possible, adding it to the backlog

**Comment by HamzaAlwan** [comment]
@metalwarrior665

Implemented this, and here is the [pull request](https://github.com/apify-projects/store-crawler-google-places/pull/340)
