### ISSUE TITLE
Secondary sort option for reviews

### ISSUE THREAD

**Issue by mattiashtd** [apify-projects/store-crawler-google-places#312]
Would it be okay if I added a secondary sort option for reviews so that we can get e.g. the 10 newest reviews and the 20 reviews with highest ranking?
INPUT_SCHEMA.json would then get additional parameters:
_secondaryMaxReviews_, _secondaryReviewsSort_.

The output would then have a _secondaryReviews_ field if _secondaryMaxReviews_ > 0.

**Comment by metalwarrior665** [comment]
I'm not sure it is worth it. Seems like a very niche use case and rerunning the place doesn't cost that much more.

**Comment by mattiashtd** [comment]
Alright, for us it would make things easier but I can understand that it's too niche to add it.
