### ISSUE TITLE
Add Updates from customers (ideally from JSON)

### ISSUE THREAD

**Issue by metalwarrior665** [apify-projects/store-crawler-google-places#335]
e.g. this place https://www.google.com/maps/place/Z%C3%81LO%C5%BDNA+Restaurant/@50.0385171,15.7098268,13z/data=!4m10!1m2!2m1!1srestaurants!3m6!1s0x470dcdc336c8970b:0xd7dce1fc2afc8411!8m2!3d50.0385171!4d15.7798646!15sCgtyZXN0YXVyYW50c1oNIgtyZXN0YXVyYW50c5IBCnJlc3RhdXJhbnTgAQA!16s%2Fg%2F11hfvkwdgg

**Comment by HamzaAlwan** [comment]
Added to this [pull request](https://github.com/apify-projects/store-crawler-google-places/pull/340)
