### ISSUE TITLE
 Not properly scraping "temporarilyClosed" info

### ISSUE THREAD

**Issue by El15ka** [apify-projects/store-crawler-google-places#341]
For a place which is temporarily closed scraper returns this information as false (eg [https://console.apify.com/actors/nwua9Gu5YrADL7ZDj/runs/e6jUDoCmD8ZLYelIC#storage](url) but as true when using url in the input: [https://api.apify.com/v2/datasets/3DSg6kFwWyc8YDUK8/items?clean=true&format=json](url)

Related issue by user: [https://console.apify.com/actors/nwua9Gu5YrADL7ZDj#/issues/o3ThmmKmgEM7MS56N/comments](url)

**Comment by metalwarrior665** [comment]
@HamzaAlwan

**Comment by HamzaAlwan** [comment]
Added to this [pull request](https://github.com/apify-projects/store-crawler-google-places/pull/340)
