### ISSUE TITLE
Price and description don't work in Chinese language (and probably other non-latin)

### ISSUE THREAD

**Issue by metalwarrior665** [apify-projects/store-crawler-google-places#352]
Example run:

https://console.apify.com/actors/nwua9Gu5YrADL7ZDj/runs/UxaQ7kSifmips7BAY#storage

place
https://www.google.com/maps/place/Hotel+San+Francisco/@37.7939831,-122.4038752,17z/data=!3m1!4b1!4m6!3m5!1s0x8085808afb840001:0xb87cd729459fcd56!8m2!3d37.7939831!4d-122.4038752!16s%2Fg%2F11ghft5z8f?hl=zh-CN

**Comment by HamzaAlwan** [comment]
@metalwarrior665,

Fixed here in this [pull request](https://github.com/apify-projects/store-crawler-google-places/pull/353)

**Comment by metalwarrior665** [comment]
Done
