### ISSUE TITLE
Nearby hotels addition

### ISSUE THREAD

**Issue by HALAMHA** [apify-projects/store-crawler-google-places#354]
Nearby hotels are not returned in the results, described in this [Slack thread](https://apifier.slack.com/archives/C01GVMUSRUN/p1676986222636499)

**Comment by HamzaAlwan** [comment]
@HALAMHA ,

Added in this [pull request](https://github.com/apify-projects/store-crawler-google-places/pull/353).

**Comment by metalwarrior665** [comment]
Done
