### ISSUE TITLE
"Place is outside of required location (polygon)" should be smarter

### ISSUE THREAD

**Issue by metalwarrior665** [apify-projects/store-crawler-google-places#87]
The problem is right now that each place is checked for being in the one specific polygon. But that is too strict. If you search the whole country, there is no need to throw away places from nearby polygons. We should instead cross-check this with all available polygons and make sure no duplicate places are pushed.

**Comment by metalwarrior665** [comment]
Actually, my assumption is maybe wrong and it counts with all correct locations as it should. Need to dig deeper.

**Comment by pocesar** [comment]
using this always gives "[PLACE]: Place is outside of required location (polygon), skipping...":

```json
  "searchStringsArray": [
    "vetement"
  ],
  "maxCrawledPlaces": 10,
  "language": "en",
  "maxReviews": 1,
  "maxImages": 1,
  "includeHistogram": false,
  "includeOpeningHours": false,
  "includePeopleAlsoSearch": false,
  "additionalInfo": false,
  "reviewsSort": "mostRelevant",
  "exportPlaceUrls": false,
  "country": "France",
  "postalCode": "75016",
  "proxyConfig": {
    "useApifyProxy": true,
    "apifyProxyGroups": [
      "SHADER"
    ]
  }
}
```

**Comment by Mozez20** [comment]
> using this always gives "[PLACE]: Place is outside of required location (polygon), skipping...":
> 
> ```json
>   "searchStringsArray": [
>     "vetement"
>   ],
>   "maxCrawledPlaces": 10,
>   "language": "en",
>   "maxReviews": 1,
>   "maxImages": 1,
>   "includeHistogram": false,
>   "includeOpeningHours": false,
>   "includePeopleAlsoSearch": false,
>   "additionalInfo": false,
>   "reviewsSort": "mostRelevant",
>   "exportPlaceUrls": false,
>   "country": "France",
>   "postalCode": "75016",
>   "proxyConfig": {
>     "useApifyProxy": true,
>     "apifyProxyGroups": [
>       "SHADER"
>     ]
>   }
> }
> ```

Same, postalCode isn't working.

**Comment by falkenbach** [comment]
Update: in current version example above still have all places dropped by City-ZIP Geolocation checkup:

2021-05-02T10:57:40.284Z INFO  [Geolocation]: Location found: Ile-de-France, Metropolitan France, 75016, France, lat: 48.854928, long: 2.2553299092855017
in fact its Paris and ZIP for this latt-long is Bd Périphérique, 75016 Paris, France so ZIP code works by itself, places which parsed do not match, i.e.
    "coordinates": {
      "lat": 48.8439921,
      "lng": 2.2374868
    }

**Comment by metalwarrior665** [comment]
The initial assumption was wrong, let's continue in different issues
